plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.agricaretrade.fencing'
    compileSdk 36

    defaultConfig {
    applicationId 'com.agricaretrade.fencing'
    minSdk 24
    targetSdk 36
    versionCode 8
    versionName '5.3.0'

    buildConfigField 'String', 'USER_NOTIFICATION_URL', '"https://script.google.com/macros/s/AKfycbyMQSkfNWEO7sI96-0dCgZ4yED-Ps9n7eLSB4Jh0URu0_X6Rjf9Vv3Rf8feaVdEXhEG/exec"'
}

buildFeatures {
    buildConfig true
}

buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'

    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
}
